version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
  php:
    build: ./php
    volumes:
      - ./code:/var/www/html
      - ./php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  db:
    image: mysql:8.0
    volumes:
        - "./db/:/var/lib/mysql:rw,delegated"
    environment:
      MYSQL_USER: vlad
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

